#server.port= 8082
#spring.config.activate.on-profile= prod
#open.api.title= API document
#open.api.version= v1.0.0
#open.api.description= Mota API service
#open.api.serverUrl= http://localhost:${server.port}
#open.api.serverName= server prod
#
