spring:
  config:
    activate:
      on-profile: dev
server:
  port: 80
open:
  api:
    title: ${API_TITLE:DUMMY-API-TITLE}
    version: v1.0.0
    description: Mota API service
    serverUrl: http://localhost:${server.port}
    serverName: server dev

