#server.port= 8080
#spring.config.activate.on-profile= dev
#open.api.title= API document
#open.api.version= v1.0.0
#open.api.description= Mota API service
#open.api.serverUrl= http://localhost:${server.port}
#open.api.serverName= server dev
#
